# Generated by Django 3.2.5 on 2021-07-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_remove_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='categories',
        ),
    ]
