# Generated by Django 3.2.5 on 2021-07-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_alter_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='item',
        ),
    ]
