# Generated by Django 3.1.5 on 2021-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0014_auto_20210713_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, default=33, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
