# Generated by Django 3.1.5 on 2021-07-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0016_auto_20210713_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['user', '-created_at']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='user',
        ),
    ]
